### ISSUE TITLE
Allow a YAML metadata block at the top of the file

### ISSUE THREAD

**Issue by briandk** [briandk/transcriptase#27]
It should be optional, but would allow people to specify metadata, as in a pandoc/RMarkdown document:

```yaml
---
title: "Analyzing 'Will There Be Enough Freshwater?' Year 2"
date: 2017-03-14
author: Brian A. Danielak
---
```
