### ISSUE TITLE
Fix yarn support in CircleCI

### ISSUE THREAD

**Issue by briandk** [briandk/transcriptase#35]
This should be all we need:

```yaml
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

test:
  override:
    - yarn test
```

https://circleci.com/docs/1.0/yarn/#nav-button
